### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Gbury** [c-cube/ocaml-minisat#4]
While trying to benchmark the minisat bindings, I happened upon an assertion failure.
Step to reproduce:
- `git clone 56266b163c4a1b00b4e5949398dac537757c5bad`
- `cd sat_bench`
- `git checkout  56266b163c4a1b00b4e5949398dac537757c5bad`
- `make`
- `./main.native problems/pigeon/hole6.cnf`

Produces:
`Fatal error: exception File "src/Minisat.ml", line 12, characters 15-21: Assertion failed`

**Comment by Gbury** [comment]
Ah, seems like negative atoms must be create manually, instead of using `-1` as a shorthand for the negation of atom `1`, is there a particular reason for that ?

**Comment by Gbury** [comment]
In any case, this should probably be documented in the documentation of the `Lit` module, which is currently rather minimal (cf https://c-cube.github.io/ocaml-minisat/0.1/Minisat.Lit.html )

**Comment by c-cube** [comment]
There is a reason for that: negative literals are not actually negative.

**Comment by c-cube** [comment]
By which I mean that minisat encodes negative literals as odd integers, and positive as even integers. It should probably be documented indeed.
